version: '3'

services:
    php-5.3:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-5.3
        ports:
            - "8080:80"
        restart: unless-stopped
        volumes:
            - ./www:/var/www
            - ./pear:/usr/share/php    
