version: '3'

services:
    php-5.3:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-5.3
        ports:
            - "8080:80"
            - "444:443"
            - "8081:81"
            - "445:445"
        restart: unless-stopped
        volumes:
            - ./www:/var/www
            - ./pear:/usr/share/php
            - ./apache2.conf:/etc/apache2/apache2.conf
            - ./ports.conf:/etc/apache2/ports.conf
            - ./default.conf:/etc/apache2/sites-available/default
            - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl
            - ./log:/var/log/apache2    
            - /etc/letsencrypt/archive:/var/imported/ssl